additional:
  # temporarily include repos manually # https://github.com/github/docs/issues/3630
  - "node-oas-schemas"
  - "node-oas-request"
  - "node-api-problem"
  - "node-smart-promise"
  - "node-pretty-exceptions"
  - "node-oas-fastify"
  - "node-terraform-unidiff"
  - "node-glob-promise"
  - "node-ahmad"

files:
  - "!**.js"
  - "!README.md"
  - "!docs/README.md"
  - "!colophon.yml"
  - "!package*.json"
  - "!**/template-sync.yml"
